# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/gui2.ui'
#
# Created: Sat Sep 22 22:30:48 2012
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(660, 480)
        self.toolBox = QtGui.QToolBox(Form)
        self.toolBox.setGeometry(QtCore.QRect(10, 20, 621, 421))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.groupBox = QtGui.QGroupBox(self.page_3)
        self.groupBox.setGeometry(QtCore.QRect(50, 60, 531, 201))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.btn_agregar = QtGui.QPushButton(self.groupBox)
        self.btn_agregar.setEnabled(True)
        self.btn_agregar.setGeometry(QtCore.QRect(420, 120, 95, 31))
        self.btn_agregar.setObjectName(_fromUtf8("btn_agregar"))
        self.layoutWidget_2 = QtGui.QWidget(self.groupBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(30, 40, 274, 33))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.le_due = QtGui.QLineEdit(self.layoutWidget_2)
        self.le_due.setObjectName(_fromUtf8("le_due"))
        self.horizontalLayout.addWidget(self.le_due)
        self.btn_buscar = QtGui.QPushButton(self.layoutWidget_2)
        self.btn_buscar.setObjectName(_fromUtf8("btn_buscar"))
        self.horizontalLayout.addWidget(self.btn_buscar)
        self.layoutWidget_3 = QtGui.QWidget(self.groupBox)
        self.layoutWidget_3.setGeometry(QtCore.QRect(30, 150, 361, 23))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lbl_nombre = QtGui.QLabel(self.layoutWidget_3)
        self.lbl_nombre.setObjectName(_fromUtf8("lbl_nombre"))
        self.horizontalLayout_3.addWidget(self.lbl_nombre)
        self.lbl_carrera = QtGui.QLabel(self.layoutWidget_3)
        self.lbl_carrera.setObjectName(_fromUtf8("lbl_carrera"))
        self.horizontalLayout_3.addWidget(self.lbl_carrera)
        self.layoutWidget_4 = QtGui.QWidget(self.groupBox)
        self.layoutWidget_4.setGeometry(QtCore.QRect(30, 100, 361, 23))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.layoutWidget_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.layoutWidget_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_19 = QtGui.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(0, 10, 191, 21))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 621, 281))
        self.page.setObjectName(_fromUtf8("page"))
        self.groupBox_2 = QtGui.QGroupBox(self.page)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 30, 571, 261))
        self.groupBox_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.btn_oagregar = QtGui.QPushButton(self.groupBox_2)
        self.btn_oagregar.setEnabled(True)
        self.btn_oagregar.setGeometry(QtCore.QRect(450, 120, 95, 31))
        self.btn_oagregar.setObjectName(_fromUtf8("btn_oagregar"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 80, 371, 33))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.le_carnet = QtGui.QLineEdit(self.layoutWidget)
        self.le_carnet.setObjectName(_fromUtf8("le_carnet"))
        self.horizontalLayout_4.addWidget(self.le_carnet)
        self.layoutWidget_5 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget_5.setGeometry(QtCore.QRect(30, 120, 371, 33))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_11 = QtGui.QLabel(self.layoutWidget_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_5.addWidget(self.label_11)
        self.le_nombre = QtGui.QLineEdit(self.layoutWidget_5)
        self.le_nombre.setEnabled(True)
        self.le_nombre.setObjectName(_fromUtf8("le_nombre"))
        self.horizontalLayout_5.addWidget(self.le_nombre)
        self.layoutWidget_6 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget_6.setGeometry(QtCore.QRect(30, 170, 371, 33))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_12 = QtGui.QLabel(self.layoutWidget_6)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_6.addWidget(self.label_12)
        self.le_apellido = QtGui.QLineEdit(self.layoutWidget_6)
        self.le_apellido.setEnabled(True)
        self.le_apellido.setObjectName(_fromUtf8("le_apellido"))
        self.horizontalLayout_6.addWidget(self.le_apellido)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(210, 220, 371, 31))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_21 = QtGui.QLabel(self.groupBox_2)
        self.label_21.setGeometry(QtCore.QRect(20, 10, 371, 31))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.layoutWidget_7 = QtGui.QWidget(self.page_4)
        self.layoutWidget_7.setGeometry(QtCore.QRect(160, 20, 274, 33))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_13 = QtGui.QLabel(self.layoutWidget_7)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_7.addWidget(self.label_13)
        self.le_codigo = QtGui.QLineEdit(self.layoutWidget_7)
        self.le_codigo.setObjectName(_fromUtf8("le_codigo"))
        self.horizontalLayout_7.addWidget(self.le_codigo)
        self.btn_buscar_2 = QtGui.QPushButton(self.layoutWidget_7)
        self.btn_buscar_2.setObjectName(_fromUtf8("btn_buscar_2"))
        self.horizontalLayout_7.addWidget(self.btn_buscar_2)
        self.layoutWidget_8 = QtGui.QWidget(self.page_4)
        self.layoutWidget_8.setGeometry(QtCore.QRect(120, 90, 361, 23))
        self.layoutWidget_8.setObjectName(_fromUtf8("layoutWidget_8"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.lbl_nombre_2 = QtGui.QLabel(self.layoutWidget_8)
        self.lbl_nombre_2.setObjectName(_fromUtf8("lbl_nombre_2"))
        self.horizontalLayout_8.addWidget(self.lbl_nombre_2)
        self.lbl_carrera_2 = QtGui.QLabel(self.layoutWidget_8)
        self.lbl_carrera_2.setObjectName(_fromUtf8("lbl_carrera_2"))
        self.horizontalLayout_8.addWidget(self.lbl_carrera_2)
        self.layoutWidget_9 = QtGui.QWidget(self.page_4)
        self.layoutWidget_9.setGeometry(QtCore.QRect(120, 60, 361, 23))
        self.layoutWidget_9.setObjectName(_fromUtf8("layoutWidget_9"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_16 = QtGui.QLabel(self.layoutWidget_9)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_9.addWidget(self.label_16)
        self.label_17 = QtGui.QLabel(self.layoutWidget_9)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_9.addWidget(self.label_17)
        self.label_18 = QtGui.QLabel(self.page_4)
        self.label_18.setGeometry(QtCore.QRect(370, 240, 141, 31))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.lbl_diastotal = QtGui.QLabel(self.page_4)
        self.lbl_diastotal.setGeometry(QtCore.QRect(530, 240, 61, 31))
        self.lbl_diastotal.setObjectName(_fromUtf8("lbl_diastotal"))
        self.label_20 = QtGui.QLabel(self.page_4)
        self.label_20.setGeometry(QtCore.QRect(20, 140, 141, 31))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.widget = QtGui.QWidget(self.page_4)
        self.widget.setGeometry(QtCore.QRect(90, 180, 412, 28))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.chk_lun = QtGui.QCheckBox(self.widget)
        self.chk_lun.setObjectName(_fromUtf8("chk_lun"))
        self.horizontalLayout_10.addWidget(self.chk_lun)
        self.chk_mar = QtGui.QCheckBox(self.widget)
        self.chk_mar.setObjectName(_fromUtf8("chk_mar"))
        self.horizontalLayout_10.addWidget(self.chk_mar)
        self.chk_mier = QtGui.QCheckBox(self.widget)
        self.chk_mier.setObjectName(_fromUtf8("chk_mier"))
        self.horizontalLayout_10.addWidget(self.chk_mier)
        self.chk_jue = QtGui.QCheckBox(self.widget)
        self.chk_jue.setObjectName(_fromUtf8("chk_jue"))
        self.horizontalLayout_10.addWidget(self.chk_jue)
        self.chk_vier = QtGui.QCheckBox(self.widget)
        self.chk_vier.setObjectName(_fromUtf8("chk_vier"))
        self.horizontalLayout_10.addWidget(self.chk_vier)
        self.toolBox.addItem(self.page_4, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 621, 281))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.cmb_carrera = QtGui.QComboBox(self.page_2)
        self.cmb_carrera.setGeometry(QtCore.QRect(140, 100, 161, 31))
        self.cmb_carrera.setObjectName(_fromUtf8("cmb_carrera"))
        self.lbl_ganador = QtGui.QLabel(self.page_2)
        self.lbl_ganador.setGeometry(QtCore.QRect(110, 220, 231, 21))
        self.lbl_ganador.setObjectName(_fromUtf8("lbl_ganador"))
        self.label_7 = QtGui.QLabel(self.page_2)
        self.label_7.setGeometry(QtCore.QRect(70, 190, 67, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.btn_rifa = QtGui.QPushButton(self.page_2)
        self.btn_rifa.setGeometry(QtCore.QRect(340, 100, 95, 31))
        self.btn_rifa.setObjectName(_fromUtf8("btn_rifa"))
        self.label_10 = QtGui.QLabel(self.page_2)
        self.label_10.setGeometry(QtCore.QRect(70, 70, 131, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_8 = QtGui.QLabel(self.page_2)
        self.label_8.setGeometry(QtCore.QRect(390, 190, 67, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lbl_codigo = QtGui.QLabel(self.page_2)
        self.lbl_codigo.setGeometry(QtCore.QRect(400, 220, 67, 21))
        self.lbl_codigo.setObjectName(_fromUtf8("lbl_codigo"))
        self.toolBox.addItem(self.page_2, _fromUtf8(""))

        self.retranslateUi(Form)
        self.toolBox.setCurrentIndex(3)
        QtCore.QObject.connect(self.le_due, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.btn_buscar.click)
        QtCore.QObject.connect(self.le_carnet, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.le_nombre.setFocus)
        QtCore.QObject.connect(self.le_nombre, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.le_apellido.setFocus)
        QtCore.QObject.connect(self.le_apellido, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.btn_oagregar.click)
        QtCore.QObject.connect(self.le_codigo, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.btn_buscar_2.click)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.le_due, self.btn_buscar)
        Form.setTabOrder(self.btn_buscar, self.btn_agregar)
        Form.setTabOrder(self.btn_agregar, self.le_carnet)
        Form.setTabOrder(self.le_carnet, self.le_nombre)
        Form.setTabOrder(self.le_nombre, self.le_apellido)
        Form.setTabOrder(self.le_apellido, self.btn_oagregar)
        Form.setTabOrder(self.btn_oagregar, self.cmb_carrera)
        Form.setTabOrder(self.cmb_carrera, self.btn_rifa)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Ingenieria Y Arquitectura", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_agregar.setText(QtGui.QApplication.translate("Form", "Agregar", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "DUE:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_buscar.setText(QtGui.QApplication.translate("Form", "Buscar", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_nombre.setText(QtGui.QApplication.translate("Form", "@Nombres + @Apellidos", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_carrera.setText(QtGui.QApplication.translate("Form", "@Carrera", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Nombres", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Carrera", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Form", "DUE del estudiante a buscar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), QtGui.QApplication.translate("Form", "Inscribir Participantes", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_oagregar.setText(QtGui.QApplication.translate("Form", "Agregar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "DUI ó Carnet", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "Nombre         ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Form", "Apellidos      ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Inscripción en caso que no tenga DUE el participante", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Form", "Información del participante:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QtGui.QApplication.translate("Form", "Inscribir Otros", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Form", "DUE ó Código", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_buscar_2.setText(QtGui.QApplication.translate("Form", "Buscar", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_nombre_2.setText(QtGui.QApplication.translate("Form", "@Nombres + @Apellidos                 ", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_carrera_2.setText(QtGui.QApplication.translate("Form", "@Carrera", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Form", "Nombres                                              ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Form", "Carrera", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Form", "Total Días Asistidos:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_diastotal.setText(QtGui.QApplication.translate("Form", "@Total", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Form", "Días Asistidos:", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_lun.setText(QtGui.QApplication.translate("Form", "Lunes", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_mar.setText(QtGui.QApplication.translate("Form", "Martes", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_mier.setText(QtGui.QApplication.translate("Form", "Miércoles", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_jue.setText(QtGui.QApplication.translate("Form", "Jueves", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_vier.setText(QtGui.QApplication.translate("Form", "Viernes", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), QtGui.QApplication.translate("Form", "Asistencia", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_ganador.setText(QtGui.QApplication.translate("Form", "@Nombre + @Apellido", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Ganador:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_rifa.setText(QtGui.QApplication.translate("Form", "Iniciar Rifa", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Carrera según día:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Código", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_codigo.setText(QtGui.QApplication.translate("Form", "@Codigo", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QtGui.QApplication.translate("Form", "Rifa", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

